name: G-Task Nexus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - uses: NuGet/setup-nuget@v2
      - run: nuget restore "G-Task Nexus/GTaskNexus.sln"
      - run: msbuild "G-Task Nexus/GTaskNexus.sln" /p:Configuration=Release /p:PublishSingleFile=true
      - uses: actions/upload-artifact@v4
        with:
          name: G-Task-Nexus-Portable
          path: "G-Task Nexus/bin/Release/**/GTaskNexus.exe"
